### ISSUE TITLE
Use a trait for template_path

### ISSUE THREAD

**Issue by blink1073** [janfreyberg/matlab_nbconvert#2]
I believe you need to use a trait with a default value for the template path, I'm getting this warning:

```
[NbConvertApp] WARNING | Config option `template_path` not recognized by `MatlabExporter`.  Did you mean one of: `template_extension, template_file`?
[NbConvertApp] Converting notebook octavemagic_extension.ipynb to matlab
[NbConvertApp] Writing 2537 bytes to octavemagic_extension.m
```

**Comment by janfreyberg** [comment]
Thanks for flagging this, I had issues with getting the template_path to work. The [docs](http://nbconvert.readthedocs.io/en/latest/external_exporters.html) suggested this:
```
    @property
    def template_path(self):
        """
        We want to inherit from HTML template, and have template under
        `./templates/` so append it to the search path. (see next section)
        """
        return super().template_path+[os.path.join(os.path.dirname(__file__), "templates")]
```

But this actually yields an error (since other methods expect `template_path` to be a list and not a method). I'm not getting that warning right now. Which version of nbconvert do you have installed?
